### PR TITLE
Upgrade to 2.3.7

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by fonnesbeck** [comment]
PyPI is currently not letting me upload files. I assume this is temporary, and will try again soon.

**Comment by kyleabeauchamp** [comment]
SGTM, I currently have the recipe downloading from the github release if that's OK with you.

**Comment by fonnesbeck** [comment]
Ah, great. That's probably better anyhow.

**Comment by kyleabeauchamp** [comment]
So I've added an openblas requirement, as I've found that we end up with dynamic linker errors without having it installed.

**Comment by fonnesbeck** [comment]
Great, so this does not require changes to the release on the PyMC side?

**Comment by kyleabeauchamp** [comment]
I don't think so, it's just a matter of formalizing the fact that the library is linking to openblas and requiring that those libraries are present during runtime.

**Comment by kyleabeauchamp** [comment]
I think this is good to merge.

**Pull request merged**
