### PR TITLE
Remove numpy 112 exclusion

### PR DESCRIPTION
**Pull request by kyleabeauchamp**
cc @fonnesbeck 

I don't know if this is permissible or not.  There were some reports of issues with np112 on Windows, but I'm not certain that those reports were observed on non-windows platforms.

### CODE REVIEW

**Comment by ocefpaf** [comment]
@kyleabeauchamp what is the minimum version of `numpy`? If it is `numpy 1.11` you can do:

```yaml
build:
  numpy 1.11.*
run:
  numpy >=1.11
```

and then re-render. If you want to support more `numpy` versions see https://github.com/conda-forge/netcdf4-feedstock/blob/master/recipe/meta.yaml for an example of the lower limits we have in conda-forge at the moment.

**Comment by kyleabeauchamp** [comment]
I would think that anything above 1.8 would work (https://github.com/pymc-devs/pymc/blob/master/pymc-requirements#L2).  Do we need to add one line for every possible numpy version or does the current recipe work.

**Comment by ocefpaf** [comment]
> I would think that anything above 1.8 would work (https://github.com/pymc-devs/pymc/blob/master/pymc-requirements#L2).

Nice!

> Do we need to add one line for every possible numpy version or does the current recipe work.

For that scenario you can use exactly the combination in the [recipe](https://github.com/conda-forge/netcdf4-feedstock/blob/master/recipe/meta.yaml) I sent to you above. The goal is to build with the oldest `numpy` possible/available and then run with any versions that is backwards compatible.

Note that we don't have `numpy 1.8` everywhere and that is why we use `1.9` or `1.11` for some Windows+Python combinations.

**Comment by kyleabeauchamp** [comment]
What about numpy 1.12?  That recipe doesn't list it.

**Comment by ocefpaf** [comment]
> What about numpy 1.12? That recipe doesn't list it.

That is exactly my the point above! If you build with `numpy 1.8.*` and add `numpy >=1..8` to run you'll be able to use any version that is `>=1.8`. Just bare in mind the caveat I mentioned above regarding the numpy versions available to build against.

**Comment by kyleabeauchamp** [comment]
Updated with numpy grid from netcdf4

**Comment by ocefpaf** [comment]
OK. Now you need to bump the build number, so a new package gets created, and then you'll need to rerender. See https://conda-forge.org/docs/conda_smithy.html for the instructions on re-rendering.

**Comment by kyleabeauchamp** [comment]
I'm concerned about removing the numpy x.x.  This package compiles fortran code that interacts with numpy, which to me means that we need to build a separate build for each numpy version.

**Comment by ocefpaf** [comment]
> I'm concerned about removing the numpy x.x.  This package compiles fortran code that interacts with numpy, which to me means that we need to build a separate build for each numpy version.  

https://conda-forge.org/docs/meta.html#building-against-numpy

**Comment by kyleabeauchamp** [comment]
Updated the build number, but I can't seem to get either `conda smithy rerender` or `conda-smithy rerender` working.  Seems like the executable is not installed.

**Comment by ocefpaf** [comment]
That is odd. I can do that for you then. Hold on...

**Comment by isuruf** [comment]
> Updated the build number, but I can't seem to get either conda smithy rerender or conda-smithy rerender working. Seems like the executable is not installed. I'm in the root env, FWIW.

@ocefpaf, can this be an issue with noarch? @kyleabeauchamp what's the version of conda-smithy you are using? (You can check by running `conda list`)

**Comment by kyleabeauchamp** [comment]
```
conda list|grep smith
conda-smithy              2.4.0                      py_1    conda-forge
```

**Comment by kyleabeauchamp** [comment]
PS: I would like to wait for @fonnesbeck to reply before we push this update live, as he is the primary maintainer of pymc.

**Comment by ocefpaf** [comment]
> @ocefpaf, can this be an issue with noarch?

Don't think so, I've been using it non-stop without a problem since the release.

**Comment by ocefpaf** [comment]
Closing this in favor of #3

**Pull request closed without merging**
