### PR TITLE
[WIP] Update recipe to 2.3.7.rc1, re-render.

### PR DESCRIPTION
**Pull request by kyleabeauchamp**

### CODE REVIEW

**Comment by kyleabeauchamp** [comment]
Does anyone know if the Travis OSX queue is really 12 hours long or is something else wrong?

**Comment by ocefpaf** [comment]
> Does anyone know if the Travis OSX queue is really 12 hours long or is something else wrong?

Just a long queue :unamused:

**Comment by kyleabeauchamp** [comment]
still waiting, 2 days later :(

**Comment by fonnesbeck** [comment]
Yep, appears to be system wide, and on Linux as well. I’ve got a PyMC3 release candidate waiting as well.

**Comment by ocefpaf** [comment]
Due to the long queue it is fine merging this to "cash" the other packages and watch master for OS X (Travis-CI).

**Comment by fonnesbeck** [comment]
Thanks.

**Comment by fonnesbeck** [comment]
@kyleabeauchamp how do we get this to show up on the conda channel?

**Comment by kyleabeauchamp** [comment]
I don't know.  It looks like the linux builds worked just fine, but the OSX builds never built, either due to bugs in the recipe upgrade or due to the infinite queue.

https://anaconda.org/conda-forge/pymc/files

**Comment by kyleabeauchamp** [comment]
According to history, seems like the most recent build was this PR and was cancelled: https://travis-ci.org/conda-forge/pymc-feedstock/builds

**Comment by kyleabeauchamp** [comment]
Looks like OSX builds are starting to appear online.

**Comment by fonnesbeck** [comment]
@kyleabeauchamp Yep, they are there. It installs fine on my machine. Happy for me to tag a release?

**Comment by kyleabeauchamp** [comment]
I checked that my environment installed the RC, that the import worked fine, tests pass, and that my current project works with the new conda build.  Thus, I think we're good.

**Pull request merged**
