### PR TITLE
ENH: Add python-graphviz to the list of requirements for the full pymc recipe

### PR DESCRIPTION
**Pull request by lucianopaz**
# Merge this branch into the next release

…c recipe

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

This should add python-graphviz as a requirement of the pymc recipe

### CODE REVIEW

**Comment by maresb** [comment]
This looks fine, but how urgent is this? Could it wait for the next release? Changing the dependencies without changing the version can lead to confusion.

Just in terms of context/documentation, could you please explain a bit about the motivation? It increases the size of the environment by about 100MB, which might be enough for people to raise questions. Is it just for using `model_to_graphviz`?

**Comment by lucianopaz** [comment]
Yes, this isn’t urgent or anything, and yes, it’s only to be able to draw `model_to_graphviz`.

**Comment by maresb** [comment]
Ok, great! Thanks for clarifying. Let's merge this into the next patch release that comes out. In preparation I'll revert bumping the build number so that we can merge it cleanly.

**Comment by maresb** [comment]
NOOOO!!!! I forgot on v5.8.1 :man_facepalming:

**Comment by ricardoV94** [comment]
> NOOOO!!!! I forgot on v5.8.1 :man_facepalming: 

Next time

**Review by michaelosthege — APPROVED** [review]

**Pull request merged**
