### PR TITLE
4.0.0

### PR DESCRIPTION
**Pull request by twiecki**
Super-sedes https://github.com/conda-forge/pymc-feedstock/pull/36.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Review by michaelosthege — APPROVED** [review]

**Comment by maresb** [comment]
This is very exciting!!! :smile: 

I don't see `semver` in `requirements.txt`. Is it possible to remove it from the requirements, or does this break something? In case it breaks something, perhaps we should add an explanatory comment to `meta.yaml`?

**Comment by maresb** [comment]
Looks great without the `semver`!

This is probably a horribly naive question, but in #39 I removed the compiler requirements

```yaml
    - cxx-compiler  # [not win]
    - m2w64-toolchain  # [win]
```

and the package still built properly.

This is a bit surprising to me, but unfortunately it's been a while since I've used PyMC, and I know the architecture has changed massively, but that means that I don't know anymore exactly what the compilers are for. Are they optional but speed up inference by an order-of-magnitude? Are they used for on-demand compilation of the models for inference?

Assuming we want to keep the compilers, should we add some test which ensures that the compilers are configured properly?

**Comment by michaelosthege** [comment]
The compilers are optional, but make it an order of magnitude faster.

A test would be great unless it interferes with installation of the package.
It would be good to have a test that checks that there is no "NumPy C-backend not available" warning on import.
Or generally no print/warnings on import.

**Comment by maresb** [comment]
The test would run only when building the package, so it wouldn't interfere with installation.
>It would be good to have a test that checks that there is no "NumPy C-backend not available" warning on import.
Or generally no print/warnings on import.
:+1: 
I'm not sure offhand how to achieve this, but I can think about it, and if I don't come up with an idea there's always the Conda-Forge Gitter channel.

But I don't see this as a blocker. LGTM!

**Review by maresb — APPROVED** [review]

**Pull request merged**
