### PR TITLE
Convert PyMC recipe to noarch

### LINKED ISSUE #51: Convert to noarch
### Comment:

Currently we build one package (technically base/main pair) per platform per Python version. In the case when a package does not need to be built differently depending on the platform / Python version, Conda offers an alternative called a "noarch" package. In this case, just a single package is built (from Linux).

If my assumption is correct that PyMC is a purely-Python frontend to Aesara, then I think it makes sense to eventually convert this to a noarch feedstock.

An example of a noarch feedstock is [aeppl](https://github.com/conda-forge/aeppl-feedstock/blob/main/recipe/meta.yaml). It can be noarch because all of the compiler stuff is encapulated in tthe Aesara build process.

An advantage is faster, simpler builds which eat up fewer resources. A disadvantage is that we lose the multiplatform tests. (With noarch, the only tests which are run are for the build platform which is Linux.)

I think it makes sense to postpone the implementation of noarch due to the testing benefits. Once we are convinced that things are stable and that the only platform-specific differences arise are at the level of Aesara, then it makes sense to switch.

### PR DESCRIPTION
**Pull request by maresb**
After monitoring the situation for a while, I think the time has finally come to start seriously considering this. The `pymc-base` / `pymc` split seems to be working flawlessly, and all the platform-dependent stuff is taken care of by Aesara.

I'm in **no rush** to merge this. Indeed, this is slightly dangerous because we'd lose the extensive testing. (Noarch packages are only tested on Linux.) But PyMC is in principle completely platform-independent, so one hopes it should be fine.

Closes #51.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Review by twiecki — APPROVED** [review]

**Comment by twiecki** [comment]
Thanks @maresb, amazing to have gotten to this point!

**Pull request merged**
