### PR TITLE
Fix skipped test for pymc package

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
Excellent, this is now failing correctly! :smile:

**Comment by maresb** [comment]
Ok, I believe this is now ready to merge! :tada: 

Since the previous merge of #41 into `main` there are no changes which would affect the package (no dependency changes). Therefore, it should be fine to merge this with the build number `1` since creating build `2` would be pointless.

On Windows, we still see the `Could not locate executable` warnings, but they are [safe to ignore](https://github.com/conda-forge/aesara-feedstock/pull/68#issuecomment-1147759275). (Hopefully they can be [fixed soon](https://github.com/aesara-devs/aesara/pull/980).)

I do think that it would be worthwhile considering #40. Otherwise, the solver will always consider the premature build `0` where `mkl-service` (or `openblas` in the case of M1) is missing from the requirements. In particular, if some conflict prevents `mkl-service` from being installed, then the solver will choose build `0`, and we no longer can assume that `pymc >=4.0.0` will include `mkl-service`.

**Review by twiecki — APPROVED** [review]

**Comment by maresb** [comment]
Thanks @twiecki for the quick merge! :smile:

**Pull request merged**
